@contentType = application/avtivity+json
@baseUrl = https://mstdn.social

###
GET {{baseUrl}}/api/v1/accounts/108274
Content-Type: {{contentType}}

###
GET {{baseUrl}}/users/JonathanPulfer
Content-Type: {{contentType}}

###
GET {{baseUrl}}/.well-known/webfinger?resource=acct:JonathanPulfer@mstdn.social